/*
   constants.h - libusb constants

   Copyright (C) 2007 Tanaka Akira

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   This library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with this library; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*/

f(USB_CLASS_PER_INTERFACE)
f(USB_CLASS_AUDIO)
f(USB_CLASS_COMM)
f(USB_CLASS_HID)
f(USB_CLASS_PRINTER)
#ifdef USB_CLASS_PTP
f(USB_CLASS_PTP)
#endif
f(USB_CLASS_MASS_STORAGE)
f(USB_CLASS_HUB)
f(USB_CLASS_DATA)
f(USB_CLASS_VENDOR_SPEC)
f(USB_DT_DEVICE)
f(USB_DT_CONFIG)
f(USB_DT_STRING)
f(USB_DT_INTERFACE)
f(USB_DT_ENDPOINT)
f(USB_DT_HID)
f(USB_DT_REPORT)
f(USB_DT_PHYSICAL)
f(USB_DT_HUB)
f(USB_DT_DEVICE_SIZE)
f(USB_DT_CONFIG_SIZE)
f(USB_DT_INTERFACE_SIZE)
f(USB_DT_ENDPOINT_SIZE)
f(USB_DT_ENDPOINT_AUDIO_SIZE)
f(USB_DT_HUB_NONVAR_SIZE)
f(USB_MAXENDPOINTS)
f(USB_ENDPOINT_ADDRESS_MASK)
f(USB_ENDPOINT_DIR_MASK)
f(USB_ENDPOINT_TYPE_MASK)
f(USB_ENDPOINT_TYPE_CONTROL)
f(USB_ENDPOINT_TYPE_ISOCHRONOUS)
f(USB_ENDPOINT_TYPE_BULK)
f(USB_ENDPOINT_TYPE_INTERRUPT)
f(USB_MAXINTERFACES)
f(USB_MAXALTSETTING)
f(USB_MAXCONFIG)
f(USB_REQ_GET_STATUS)
f(USB_REQ_CLEAR_FEATURE)
f(USB_REQ_SET_FEATURE)
f(USB_REQ_SET_ADDRESS)
f(USB_REQ_GET_DESCRIPTOR)
f(USB_REQ_SET_DESCRIPTOR)
f(USB_REQ_GET_CONFIGURATION)
f(USB_REQ_SET_CONFIGURATION)
f(USB_REQ_GET_INTERFACE)
f(USB_REQ_SET_INTERFACE)
f(USB_REQ_SYNCH_FRAME)
f(USB_TYPE_STANDARD)
f(USB_TYPE_CLASS)
f(USB_TYPE_VENDOR)
f(USB_TYPE_RESERVED)
f(USB_RECIP_DEVICE)
f(USB_RECIP_INTERFACE)
f(USB_RECIP_ENDPOINT)
f(USB_RECIP_OTHER)
f(USB_ENDPOINT_IN)
f(USB_ENDPOINT_OUT)
f(USB_ERROR_BEGIN)
#ifdef LIBUSB_HAS_GET_DRIVER_NP
f(LIBUSB_HAS_GET_DRIVER_NP)
#endif
#ifdef LIBUSB_HAS_DETACH_KERNEL_DRIVER_NP
f(LIBUSB_HAS_DETACH_KERNEL_DRIVER_NP)
#endif
